config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#landing'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  before_save(:titleize_product)

  scope :most_reviews, -> { (
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}

  scope :most_recent, -> { order(created_at: :desc).limit(3) }
  scope :created_in_usa, -> { where(country_of_origin: "USA") }


  private
  
  def titleize_product
    self.name = self.name.titleize
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates_length_of :content_body, minimum: 50, maximum: 250
  validates_numericality_of :rating, greater_than: 0, less_than: 6
  before_save(:titleize_author)

  private

  def titleize_author
    self.author = self.author.titleize
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :only => [:new, :edit, :destroy] do
    flash[:alert] = "Must be an admin to continue" unless is_admin?
    redirect_to root_path unless is_admin?
  end

  def index
    @products = Product.all
    render :index
  end

  def landing
    @recent = Product.most_recent
    @origin = Product.created_in_usa
    @popular = Product.most_reviews
    render :landing
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product added!"
      redirect_to products_path
    else
      flash[:alert] = "Not able to add product! Please try again."
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product updated!"
      redirect_to products_path
    else
      flash[:alert] = "Not able to update! Please try again."
      render :edit
    end
  end

  def destroy 
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product Deleted!"
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :only => [:new, :edit, :destroy] do
    flash[:alert] = "Must be an admin to continue" unless is_admin?
    redirect_to products_path unless is_admin?
  end

  def new 
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review added!"
      redirect_to products_path(@product)
    else
      flash[:alert] = "Not able to add review! Please try again."
      render :new
    end
  end

  def edit 
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def show 
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[notice] = "Review updated!"
    else @product = Product.find(params[:product_id])
      flash[:alert] = "Review not updated! Please try again."
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:product_id])
    @review.destroy
    flash[:notice] = "Review deleted!"
    redirect_to products_path(@review.product)
  end

  private

  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :class => 'form-control' %>
  <%= f.label :cost %>
  <%= f.number_field :cost, :class => 'form-control' %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin, :class => 'form-control' %>
  <hr>
  <%= f.submit 'Add Product!', :class => "btn btn-success" %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field(:author, :class => 'form-control') %>
  <%= f.label :content_body %>
  <%= f.text_area(:content_body, :class => 'form-control') %>
  <%= f.label :rating %>
  <%= f.number_field :rating, in: 1..5, :class => 'form-control' %>
  <hr>
  <%= f.submit 'Add Review!', :class => "btn btn-success" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuadDib's Spice Emporium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <p class="flash error"><%= flash[:alert] %></p>
      <p class="flash"><%= flash[:notice] %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product!</h1>
<h2><%= @product.name %></h2>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<% if is_admin? %>
  <%= link_to "Add new product", new_product_path, :class => "btn btn-primary" %>
<% end %>
<h1>All of Marios Products:</h1>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %> - $<%= product.cost %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

app/views/products/landing.html.erb
<h1>Marios Specialty Products!</h1>
<p> Welcome to Marios! Please enjoy our products! </p>

<h2>US made products:</h2>

<% if @origin.any? %>
  <ul> 
    <% @origin.each do |product| %>
      <li><%= link_to product.name, product_path(product) %> </li>
    <% end %>
  </ul>
<% end %>

<h2>Most Recent Products:</h2>

<% if @recent.any? %>
  <ul>
    <% @recent.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% end %>



<p> If you would like to see all of marios special products, click the button below!<p>

<%= link_to "All Products", products_path, :class => "btn btn warning" %>

app/views/products/new.html.erb
<h1>Add Product:</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h2>Product Origin: <%= @product.country_of_origin %></h2>
<h3>Product Cost: $<%= @product.cost %></h3>

<% if @product.reviews.any? %>
  <h3>Reviews for <%= @product.name %></h3>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul> 
  <% end %>
<% else %>
  <p>No reviews for this product yet!</p>
<% end %>


<%= link_to "Add a review!", new_product_review_path(@product) %>
<% if is_admin? %>
  <%= link_to "Edit", edit_project_path(@product) %>
  <%= link_to "Delete", product_path(@product) :data => {:confirm => "really?",
  :method => "delete"} %>
<% end %>

<%= link_to "View All Products", products_path %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a Review</h1>
<p>Happy or not, leave a review for <%= @product.name %>!</p>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>View Review:</h1>
<h3>Author: <%= @review.author %></h3>
<h3>Rating: <%= @review.rating %> of 5</h3>
<h3>Written Review:</h3>
<p><%= @review.content_body %></p>

<% if is_admin? %>
  <%= link_to "Edit", edit_product_review_path(@product, @review) %>
  <%= link_to "Delete", product_review_path(@product, @review), :data => {:confirm => "really?",
  :method => "delete"} %>
<% end %>

<%= link_to "Return to product", product_path(@product) %>